#!/usr/bin/env python3
"""
bib2yaml.py — Converts bibliography/publications.bib to data/publications.yaml

Usage:
    python scripts/bib2yaml.py

Requires:
    pip install bibtexparser
"""

import sys
import os

try:
    import bibtexparser
    from bibtexparser.bparser import BibTexParser
    from bibtexparser.customization import convert_to_unicode
except ImportError:
    print("Error: bibtexparser not found. Install it with: pip install bibtexparser")
    sys.exit(1)

import yaml
from pathlib import Path

# Paths relative to project root
PROJECT_ROOT = Path(__file__).parent.parent
BIB_FILE = PROJECT_ROOT / "bibliography" / "publications.bib"
YAML_FILE = PROJECT_ROOT / "data" / "publications.yaml"


def parse_authors(raw: str) -> str:
    """Convert BibTeX author string to 'Lastname F, Lastname F' format."""
    authors = []
    for part in raw.split(" and "):
        part = part.strip()
        if not part:
            continue
        if "," in part:
            # "Lastname, Firstname" → "Lastname F"
            last, first = part.split(",", 1)
            initials = "".join(w[0] + "." for w in first.strip().split() if w)
            authors.append(f"{last.strip()} {initials}")
        else:
            # "Firstname Lastname" → "Lastname F"
            words = part.split()
            if len(words) >= 2:
                last = words[-1]
                initials = "".join(w[0] + "." for w in words[:-1])
                authors.append(f"{last} {initials}")
            else:
                authors.append(part)
    return ", ".join(authors)


def entry_to_dict(entry: dict) -> dict:
    """Map BibTeX fields to our YAML schema."""
    key = entry.get("ID", "")
    title = entry.get("title", "").replace("{", "").replace("}", "")
    authors_raw = entry.get("author", "")
    authors = parse_authors(authors_raw) if authors_raw else ""
    year = int(entry.get("year", 0))

    # venue: journal > booktitle > series
    venue = (
        entry.get("journal")
        or entry.get("booktitle")
        or entry.get("series")
        or ""
    ).replace("{", "").replace("}", "")

    volume = entry.get("volume", "")
    number = entry.get("number", "")
    if volume and number:
        volume_str = f"{volume}({number})"
    elif volume:
        volume_str = str(volume)
    else:
        volume_str = ""

    pages = entry.get("pages", "").replace("--", "-")
    doi = entry.get("doi", "")
    pdf = entry.get("pdf", "")
    abstract = entry.get("abstract", "").replace("{", "").replace("}", "")

    return {
        "key": key,
        "title": title,
        "authors": authors,
        "year": year,
        "venue": venue,
        "volume": volume_str,
        "pages": pages,
        "doi": doi,
        "pdf": pdf,
        "abstract": abstract,
    }


def main():
    if not BIB_FILE.exists():
        print(f"Error: {BIB_FILE} not found")
        sys.exit(1)

    parser = BibTexParser(common_strings=True)
    parser.customization = convert_to_unicode

    with open(BIB_FILE, encoding="utf-8") as f:
        db = bibtexparser.load(f, parser=parser)

    entries = [entry_to_dict(e) for e in db.entries]

    # Sort: year descending, then key alphabetically
    entries.sort(key=lambda e: (-e["year"], e["key"]))

    header = (
        "# Publications\n"
        "# AUTO-GENERATED by scripts/bib2yaml.py — do not edit manually.\n"
        "# Edit bibliography/publications.bib instead, then re-run the script.\n"
        "# Use [[cite:key]] in bios or {{< cite key=\"…\" >}} in markdown.\n\n"
    )

    data = {"publications": entries}
    yaml_str = yaml.dump(
        data,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
        width=120,
    )

    with open(YAML_FILE, "w", encoding="utf-8") as f:
        f.write(header + yaml_str)

    print(f"Written {len(entries)} publication(s) to {YAML_FILE}")


if __name__ == "__main__":
    main()
